In [ ]:
import numpy as np

torch_logits = np.load('torch_logits.npy')
print(torch_logits.shape)
print(torch_logits)

[[[-2.008  -1.338  -3.105  ...  1.249   0.2847 -3.389 ]
  [-2.008  -1.338  -3.105  ...  1.249   0.2847 -3.389 ]
  [-2.008  -1.338  -3.105  ...  1.249   0.2847 -3.389 ]
  ...
  [-2.008  -1.338  -3.105  ...  1.249   0.2847 -3.389 ]
  [-2.008  -1.338  -3.105  ...  1.249   0.2847 -3.389 ]
  [-2.008  -1.338  -3.105  ...  1.249   0.2847 -3.389 ]]]


In [ ]:
import numpy as np

torch_logits = np.load('flax_logits.npy')
print(torch_logits.shape)
print(torch_logits)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
